name: Mapcha
version: 1..
main: com.envyclient.mapcha.Mapcha
description: A simple captcha plugin, which uses maps as the captcha.

commands:
   mapcha:
     usage: /<command>
     description: Shows commands about the plugin.

permissions:
   mapcha.reload:
     desciption: Allows you to use the reload command.
     default: op
   mapcha.bypass:
     desciption: Allows you to bypass the captcha.
     default: op