name: Mapcha
version: 1.5
main: me.ihaq.mapcha.Mapcha
description: A simple captcha plugin, which uses maps as the captcha.

permissions:
  mapcha.bypass:
    desciption: Allows you to bypass the captcha.
    default: op