name: Mapcha
version: ${project.version}
main: me.affanhaq.mapcha.Mapcha
description: A simple captcha plugin, which uses maps as the captcha.

permissions:
  mapcha.bypass:
    desciption: Allows you to bypass the captcha.
    default: op