# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -B package --file pom.xml
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: mkdir staging && cp target/mapcha-hyper-${{ steps.vars.outputs.sha_short }}.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: mapcha-hyper-${{ steps.vars.outputs.sha_short }}
          path: staging